# Generated by Django 4.1.7 on 2023-02-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="last name",
                    ),
                ),
                ("salary", models.PositiveIntegerField(verbose_name="salary")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="photo",
                    ),
                ),
                ("age", models.PositiveIntegerField(verbose_name="age")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="departments.department",
                        verbose_name="department",
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "unique_together": {("id", "department")},
                "ordering": ("-id",),
            },
        ),
    ]
