# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-duplicate-keys
          - --ignore-init-module-imports
          - --remove-unused-variables
          - --remove-all-unused-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-alfred",
          "flake8-bugbear",
          "flake8-builtins",
          "flake8-coding",
          "flake8-cognitive-complexity",
          "flake8-commas",
          "flake8-comprehensions",
          "flake8-debugger",
          "flake8-eradicate",
          "flake8-isort",
          "flake8-logging-format",
          "flake8-multiline-containers",
          "flake8-pep3101",
          "flake8-print",
          "flake8-pytest-style",
          "flake8-quotes",
          "flake8-return",
          "flake8-simplify",
          "flake8-sql",
          #            "flake8-annotations",
        ]
